version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "ninjadb"
      POSTGRES_USER: "ninja"
      POSTGRES_PASSWORD: "visibleNinja"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
      
  dbadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ninja@debt-ninja.io"
      PGADMIN_DEFAULT_PASSWORD: "debt-ninja"
    ports:
      - "84:80"
    depends_on:
      - db

volumes: 
  postgres: